//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDFinal
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AsdfEntities1 : DbContext
    {
        public AsdfEntities1()
            : base("name=AsdfEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendance { get; set; }
        public virtual DbSet<Studentt> Studentt { get; set; }
    }
}
