//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<System.DateTimeOffset> Date { get; set; }
    
        public virtual Studentt Studentt { get; set; }
    }
}
