USE [master]
GO

/****** Object:  Database [Asdf]    Script Date: 1/13/2017 5:01:10 PM ******/
CREATE DATABASE [Asdf]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Asdf', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRES2012\MSSQL\DATA\Asdf.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Asdf_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRES2012\MSSQL\DATA\Asdf_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Asdf] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Asdf].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Asdf] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Asdf] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Asdf] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Asdf] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Asdf] SET ARITHABORT OFF 
GO

ALTER DATABASE [Asdf] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Asdf] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Asdf] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Asdf] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Asdf] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Asdf] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Asdf] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Asdf] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Asdf] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Asdf] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Asdf] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Asdf] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Asdf] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Asdf] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Asdf] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Asdf] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Asdf] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Asdf] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Asdf] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Asdf] SET  MULTI_USER 
GO

ALTER DATABASE [Asdf] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Asdf] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Asdf] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Asdf] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Asdf] SET  READ_WRITE 
GO


